// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frvgdouwulzqtcsrqqkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydmdkb3V3dWx6cXRjc3JxcWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjgzOTMsImV4cCI6MjA2NjQwNDM5M30.YstVus6mcpMTaUo29hmDiQofs0qCZ7bj1uAsBh2Rv_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);